/* Semua teks landing page, dua bahasa. Elemen HTML memakai data-i18n="kunci";
   app.js mengganti isinya sesuai bahasa. Satu tempat buat brand + tanggal launching. */
'use strict';

const BRAND = 'XyVerse Technology Global';
const REPO = 'xykal/wa-release-bot';
// Launching publik: Jumat 9 Oktober 2026, 19.00 WIB (= 12.00 UTC). Diputuskan kall 2026-09-29.
const LAUNCH_ISO = '2026-10-09T12:00:00Z';
const VERSI_LAUNCH = '1.0.0';

const TEKS = {
  id: {
    nav_fitur: 'Fitur', nav_cara: 'Cara kerja', nav_faq: 'FAQ', nav_unduh: 'Unduh APK', nav_github: 'GitHub',
    hero_label: 'Bot WhatsApp yang jalan dari HP Android kamu sendiri',
    hero_judul: 'Rilis GitHub langsung ke channel WhatsApp. Tanpa server.',
    hero_sub: 'WA Release Bot ngumumin tiap release baru ke channel atau grup WA, jagain permintaan gabung grup, dan ngirim lagu harian biar channel nggak sepi. Semuanya dari satu APK, nggak perlu VPS, laptop, atau Termux.',
    hero_cta: 'Unduh APK', hero_cta2: 'Lihat kode di GitHub',
    hero_poin1: 'Node.js 18 beneran di dalam APK', hero_poin2: 'WhatsApp cuma nyambung pas mau kirim', hero_poin3: 'Token dan sesi tetap di HP kamu',
    masalah_judul: 'Kenal sama yang ini?',
    masalah1_j: 'Grup kemasukan akun spam jam dua pagi', masalah1_i: 'Penjaga grup nyaring permintaan gabung satu-satu. Yang dulu udah keluar atau pernah dikeluarin, ditolak otomatis.',
    masalah2_j: 'Channel sepi kayak kuburan', masalah2_i: 'Tiap hari bot ngirim potongan lagu 60 detik sebagai voice note, lengkap dengan caption yang dibikin AI.',
    masalah3_j: 'Rilis aplikasi lupa diumumin', masalah3_i: 'Begitu ada tag baru di GitHub, bot posting: apa yang baru, file yang bisa diunduh, sampai ukurannya.',
    fitur_judul: 'Fitur', fitur_sub: 'Semua bisa diatur dari layar app. Nggak ada file config yang harus diedit.',
    f1_j: 'Rilis ke channel', f1_i: 'Cek release tiap 15 menit (bisa diubah), pakai ETag jadi repo yang belum berubah nggak makan kuota API. Multi repo, tiap repo baseline sendiri.',
    f2_j: 'Penjaga grup', f2_i: 'Auto-approve permintaan gabung, tolak yang pernah keluar atau dikeluarin, daftar hitam manual.',
    f3_j: 'Lagu mood harian', f3_i: '148 lagu plus yang lagi tren, dikirim sebagai voice note dengan caption 11 gaya: galau, motivasi, ayat, sampai nyindir.',
    f4_j: 'Hosting bot custom', f4_i: 'Punya bot Node.js kecil sendiri? Unggah ZIP-nya, jalan di dalam app yang sama.',
    f5_j: 'Notifikasi kalau gagal', f5_i: 'Kirim gagal tiga kali berturut-turut: notifikasi Android plus laporan ke chat kamu sendiri. Nggak ada yang hilang diam-diam.',
    f6_j: 'Tautkan sekali seumur hidup', f6_i: 'Pairing code 8 huruf tanpa HP kedua, atau QR. Sesi disimpan terenkripsi di HP.',
    cara_judul: 'Kok bisa tanpa server?', cara_sub: 'Yang dipakai di dalam APK, apa adanya.',
    cara1_j: 'Kotlin', cara1_i: 'Service Android di foreground, watchdog WorkManager, dan boot receiver. Kalau Android bunuh service-nya, dia nyala lagi.',
    cara2_j: 'Node.js 18 (nodejs-mobile)', cara2_i: 'Engine bot ditulis JavaScript dan jalan di Node beneran di dalam APK. Kode yang sama dipakai versi CLI buat Termux/PC.',
    cara3_j: 'Baileys', cara3_i: 'Protokol WhatsApp Web multi-device. Nyambung cuma beberapa detik waktu posting, sisanya tidur.',
    cara4_j: 'Cloudflare Worker + AI', cara4_i: 'Caption lagu dibikin di Worker (model Groq) dengan batas harian per perangkat. Token AI nggak pernah ada di HP.',
    siklus_judul: 'Satu siklus, 15 menit',
    siklus1: 'Bangun', siklus2: 'Cek rilis GitHub', siklus3: 'Cek permintaan gabung', siklus4: 'Kirim lagu harian (kalau jadwalnya)', siklus5: 'Tidur lagi',
    galeri_judul: 'Tampilannya', galeri_sub: 'Ilustrasi dari layar app, bukan tangkapan layar dari HP orang.',
    g_beranda: 'Beranda', g_rilis: 'Post rilis', g_grup: 'Penjaga grup', g_lagu: 'Lagu mood', g_caption: 'Caption AI', g_lapor: 'Status bot',
    aman_judul: 'Privasi dan keamanan', aman_sub: 'Botnya di HP kamu, datanya juga.',
    aman1_j: 'Nggak ada server tengah', aman1_i: 'HP kamu ngobrol langsung ke GitHub dan WhatsApp. Nggak ada akun, nggak ada dashboard, nggak ada pihak ketiga yang lihat pesan.',
    aman2_j: 'Token tetap di HP', aman2_i: 'Token GitHub (opsional, buat repo privat) dan sesi WA disimpan di penyimpanan privat app.',
    aman3_j: 'Kode bisa dilihat', aman3_i: 'Source-available di GitHub: CI publik, CodeQL, audit dependensi, APK dibangun otomatis dari tag dengan checksum SHA-256.',
    aman4_j: 'Lisensi pemakaian pribadi', aman4_i: 'Boleh dipakai dan dipelajari. Nggak boleh dijual atau disebar ulang tanpa izin.',
    faq_judul: 'Pertanyaan yang sering muncul',
    q1: 'Perlu root atau Termux?', a1: 'Nggak dua-duanya. Pasang APK, tautkan WA, isi repo dan channel, tekan Mulai.',
    q2: 'HP-nya harus nyala terus?', a2: 'Iya, ini bot yang jalan dari HP. Paling cocok buat HP nganggur yang dicolok charger. Konsumsi baterainya kecil karena WA cuma nyambung waktu ada yang mau dikirim.',
    q3: 'Nomor WA-nya kena banned nggak?', a3: 'Bot cuma ngirim ke channel atau grup milik kamu sendiri, dengan jeda wajar, bukan broadcast ke orang. Tetap pakai nomor khusus bot kalau mau lebih aman.',
    q4: 'Bisa lebih dari satu repo?', a4: 'Bisa. Isi kolom repo pakai koma, tiap repo dicek dan diumumkan terpisah.',
    q5: 'Repo privat?', a5: 'Bisa, isi token GitHub dengan scope repo di setelan. Tokennya nggak pernah keluar dari HP.',
    q6: 'Android versi berapa?', a6: 'Android 8.0 (API 26) ke atas, arm64 atau armeabi-v7a. Ada APK universal kalau nggak yakin.',
    unduh_judul: 'Unduh APK', unduh_sub: 'Dibangun otomatis di GitHub Actions dari tag rilis. Cocokkan SHA-256 sebelum pasang.',
    unduh_arm64: 'Kebanyakan HP 2018 ke atas', unduh_v7a: 'HP lama 32-bit', unduh_univ: 'Dua arsitektur sekaligus, file lebih besar',
    unduh_tombol: 'Unduh', unduh_sha: 'SHA-256', unduh_versi: 'Versi', unduh_tanggal: 'Dirilis', unduh_ukuran: 'Ukuran',
    unduh_catatan: 'Semua rilis dan changelog ada di halaman Releases GitHub.',
    unduh_gagal: 'Nggak bisa ngambil data rilis dari GitHub sekarang. Buka halaman Releases langsung.',
    modal_label: 'Segera', modal_judul: 'Launching WA Release Bot', modal_sub: 'Versi publik pertama, v' + VERSI_LAUNCH + '. APK bisa diunduh di halaman ini begitu hitung mundurnya habis.',
    hari: 'hari', jam: 'jam', menit: 'menit', detik: 'detik',
    modal_waktu: 'Jumat, 9 Oktober 2026, 19.00 WIB', modal_lokal: 'Waktu lokal kamu:',
    modal_tunggu: 'Waktunya udah lewat. File rilis lagi diunggah, halaman ini ngecek ulang tiap menit.',
    modal_ics: 'Ingatkan di kalender', modal_github: 'Pantau di GitHub', modal_kembali: 'Kembali ke beranda',
    footer_lisensi: 'Lisensi pemakaian pribadi', footer_built: 'Built by xykal',
  },
  en: {
    nav_fitur: 'Features', nav_cara: 'How it works', nav_faq: 'FAQ', nav_unduh: 'Download APK', nav_github: 'GitHub',
    hero_label: 'A WhatsApp bot that runs on your own Android phone',
    hero_judul: 'GitHub releases straight to your WhatsApp channel. No server.',
    hero_sub: 'WA Release Bot announces every new release to a WhatsApp channel or group, gatekeeps group join requests, and posts a daily song so the channel never goes quiet. All from one APK, no VPS, laptop, or Termux.',
    hero_cta: 'Download APK', hero_cta2: 'View the code on GitHub',
    hero_poin1: 'Real Node.js 18 inside the APK', hero_poin2: 'WhatsApp connects only when there is something to send', hero_poin3: 'Tokens and sessions stay on your phone',
    masalah_judul: 'Sound familiar?',
    masalah1_j: 'Spam accounts joining the group at 2 a.m.', masalah1_i: 'The gatekeeper screens every join request. Members who left or were removed before are rejected automatically.',
    masalah2_j: 'A channel as quiet as a graveyard', masalah2_i: 'Every day the bot posts a 60-second song clip as a voice note, with an AI-written caption.',
    masalah3_j: 'Forgot to announce the release again', masalah3_i: 'As soon as a new tag lands on GitHub, the bot posts what is new, the downloadable files, and their sizes.',
    fitur_judul: 'Features', fitur_sub: 'Everything is configured from the app screen. No config files to edit.',
    f1_j: 'Releases to your channel', f1_i: 'Checks every 15 minutes (adjustable) using ETags, so an unchanged repo costs no API quota. Multiple repos, each with its own baseline.',
    f2_j: 'Group gatekeeper', f2_i: 'Auto-approves join requests, rejects people who left or were removed, manual blacklist.',
    f3_j: 'Daily mood song', f3_i: '148 songs plus what is trending, sent as voice notes with captions in 11 styles: heartbreak, motivation, verses, even sarcasm.',
    f4_j: 'Host your own bot', f4_i: 'Have a small Node.js bot of your own? Upload the ZIP and it runs inside the same app.',
    f5_j: 'Failure notifications', f5_i: 'Three failed sends in a row: an Android notification plus a report to your own chat. Nothing fails silently.',
    f6_j: 'Link once, keep forever', f6_i: '8-letter pairing code without a second phone, or QR. The session is stored encrypted on the phone.',
    cara_judul: 'How does it work without a server?', cara_sub: 'What is inside the APK, as is.',
    cara1_j: 'Kotlin', cara1_i: 'A foreground Android service, WorkManager watchdog, and boot receiver. If Android kills the service, it comes back.',
    cara2_j: 'Node.js 18 (nodejs-mobile)', cara2_i: 'The bot engine is JavaScript running on real Node inside the APK. The same code powers the CLI for Termux/PC.',
    cara3_j: 'Baileys', cara3_i: 'The WhatsApp Web multi-device protocol. Connected for a few seconds while posting, asleep otherwise.',
    cara4_j: 'Cloudflare Worker + AI', cara4_i: 'Song captions are generated in a Worker (Groq models) with a daily per-device limit. The AI key never touches the phone.',
    siklus_judul: 'One cycle, 15 minutes',
    siklus1: 'Wake up', siklus2: 'Check GitHub releases', siklus3: 'Check join requests', siklus4: 'Send the daily song (when scheduled)', siklus5: 'Back to sleep',
    galeri_judul: 'What it looks like', galeri_sub: 'Illustrations of the app screens, not screenshots from someone else\u2019s phone.',
    g_beranda: 'Home', g_rilis: 'Release post', g_grup: 'Gatekeeper', g_lagu: 'Mood song', g_caption: 'AI caption', g_lapor: 'Bot status',
    aman_judul: 'Privacy and security', aman_sub: 'The bot lives on your phone, and so does its data.',
    aman1_j: 'No middle server', aman1_i: 'Your phone talks directly to GitHub and WhatsApp. No account, no dashboard, no third party reading messages.',
    aman2_j: 'Tokens stay on the phone', aman2_i: 'The GitHub token (optional, for private repos) and the WA session live in the app\u2019s private storage.',
    aman3_j: 'The code is visible', aman3_i: 'Source-available on GitHub: public CI, CodeQL, dependency audits, APKs built automatically from tags with SHA-256 checksums.',
    aman4_j: 'Personal-use license', aman4_i: 'Free to use and study. Not for resale or redistribution without permission.',
    faq_judul: 'Frequently asked questions',
    q1: 'Do I need root or Termux?', a1: 'Neither. Install the APK, link WhatsApp, fill in the repo and channel, press Start.',
    q2: 'Does the phone have to stay on?', a2: 'Yes, this bot runs from the phone. Best for a spare phone left on a charger. Battery use is small because WhatsApp only connects when there is something to send.',
    q3: 'Will my WhatsApp number get banned?', a3: 'The bot only posts to your own channel or group with sensible delays, never broadcasts to people. Use a dedicated number for the bot if you want extra safety.',
    q4: 'More than one repo?', a4: 'Yes. Separate repos with commas; each is checked and announced independently.',
    q5: 'Private repos?', a5: 'Yes, add a GitHub token with the repo scope in settings. The token never leaves the phone.',
    q6: 'Which Android version?', a6: 'Android 8.0 (API 26) or newer, arm64 or armeabi-v7a. A universal APK is available if unsure.',
    unduh_judul: 'Download APK', unduh_sub: 'Built automatically on GitHub Actions from the release tag. Verify the SHA-256 before installing.',
    unduh_arm64: 'Most phones from 2018 onwards', unduh_v7a: 'Older 32-bit phones', unduh_univ: 'Both architectures, larger file',
    unduh_tombol: 'Download', unduh_sha: 'SHA-256', unduh_versi: 'Version', unduh_tanggal: 'Released', unduh_ukuran: 'Size',
    unduh_catatan: 'All releases and the changelog are on the GitHub Releases page.',
    unduh_gagal: 'Could not load release data from GitHub right now. Open the Releases page directly.',
    modal_label: 'Coming soon', modal_judul: 'Launching WA Release Bot', modal_sub: 'First public version, v' + VERSI_LAUNCH + '. The APK becomes downloadable on this page when the countdown ends.',
    hari: 'days', jam: 'hours', menit: 'minutes', detik: 'seconds',
    modal_waktu: 'Friday, 9 October 2026, 19:00 WIB (UTC+7)', modal_lokal: 'Your local time:',
    modal_tunggu: 'The time has passed. Release files are being uploaded; this page re-checks every minute.',
    modal_ics: 'Add a calendar reminder', modal_github: 'Watch on GitHub', modal_kembali: 'Back to home',
    footer_lisensi: 'Personal-use license', footer_built: 'Built by xykal',
  },
};
