#!/usr/bin/env python3
"""Tarik literal android:text/hint/contentDescription dari layout ke strings.xml.

Kenapa skrip, bukan tangan: 80-an literal, dan nama resource harus sama persis
di layout, values/, dan values-en/. Skrip ini idempoten: literal yang sudah
@string/ dilewati. Terjemahan Inggris dibaca dari peta di bawah; literal tanpa
terjemahan dilaporkan dan TIDAK dipindah (biar values-en tidak bolong).

Pakai:  python3 scripts-dev/i18n_layout.py            # tulis
        python3 scripts-dev/i18n_layout.py --cek      # cuma laporan
"""
import json
import re
import sys
from pathlib import Path

AKAR = Path(__file__).resolve().parents[1]
LAYOUT = AKAR / "app/src/main/res/layout/activity_main.xml"
PETA = AKAR / "scripts-dev/i18n_peta.json"  # {"teks indonesia": "english"}
VALUES = AKAR / "app/src/main/res/values/strings.xml"
VALUES_EN = AKAR / "app/src/main/res/values-en/strings.xml"

# Netral bahasa: angka, tanda, URL. Dibiarkan literal.
LEWATI = re.compile(r"^(?:[\d\s—–-]+|https?://\S*)$")
ATTR = re.compile(r'(android:(?:text|hint|contentDescription)=")([^"@][^"]*)(")')


def slug(teks: str) -> str:
    t = teks.lower()
    t = re.sub(r"&\w+;", " ", t)
    t = re.sub(r"[^a-z0-9]+", "_", t).strip("_")
    kata = [k for k in t.split("_") if k][:5]
    return "u_" + "_".join(kata) if kata else "u_teks"


def escape_xml_string(teks: str) -> str:
    # Atribut layout sudah XML-escaped (&quot; &amp;); yang belum aman di
    # <string> cuma apostrof dan tanda @/? di awal.
    t = teks.replace("'", "\\'")
    if t[:1] in "@?":
        t = "\\" + t
    return t


def main() -> int:
    cek = "--cek" in sys.argv
    peta = json.loads(PETA.read_text(encoding="utf-8"))
    xml = LAYOUT.read_text(encoding="utf-8")
    nama_dari_teks: dict[str, str] = {}
    tanpa_terjemahan: list[str] = []
    dipakai: set[str] = set()

    def ganti(m: re.Match) -> str:
        teks = m.group(2)
        if LEWATI.match(teks):
            return m.group(0)
        if teks not in peta:
            if teks not in tanpa_terjemahan:
                tanpa_terjemahan.append(teks)
            return m.group(0)
        nama = nama_dari_teks.get(teks)
        if nama is None:
            nama = slug(teks)
            dasar, n = nama, 2
            while nama in dipakai:
                nama = f"{dasar}_{n}"
                n += 1
            dipakai.add(nama)
            nama_dari_teks[teks] = nama
        return f"{m.group(1)}@string/{nama}{m.group(3)}"

    xml_baru = ATTR.sub(ganti, xml)
    print(f"dipindah: {len(nama_dari_teks)} string; tanpa terjemahan: {len(tanpa_terjemahan)}")
    for t in tanpa_terjemahan:
        print("  ! " + t)
    if cek:
        return 1 if tanpa_terjemahan else 0

    if not nama_dari_teks:
        print("tidak ada yang perlu dipindah")
        return 0

    def entri_lama(path: Path) -> dict[str, str]:
        if not path.exists():
            return {}
        return dict(re.findall(r'<string name="([^"]+)">(.*?)</string>', path.read_text(encoding="utf-8"), re.S))

    def tulis(path: Path, isi: dict[str, str], komentar: str) -> None:
        # Entri yang sudah ada (mis. hasil migrasi string Kotlin) dipertahankan;
        # yang baru ditambahkan di bawahnya. Skrip ini boleh dijalankan ulang.
        gabung = entri_lama(path)
        gabung.setdefault("app_name", "WA Release Bot")
        for teks, nama in nama_dari_teks.items():
            gabung[nama] = escape_xml_string(isi[teks])
        baris = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {komentar} -->", "<resources>"]
        baris += [f'    <string name="{n}">{v}</string>' for n, v in gabung.items()]
        baris.append("</resources>")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(baris) + "\n", encoding="utf-8")

    tulis(VALUES, {t: t for t in nama_dari_teks},
          "Bahasa bawaan (Indonesia). Entri u_* dibangkitkan scripts-dev/i18n_layout.py dari layout.")
    tulis(VALUES_EN, {t: peta[t] for t in nama_dari_teks},
          "English. u_* entries generated by scripts-dev/i18n_layout.py from scripts-dev/i18n_peta.json.")
    LAYOUT.write_text(xml_baru, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
